### ISSUE TITLE
Download file broken?

### ISSUE THREAD

**Issue by bbluemel** [alexandrusavin/nodejs-putiosdk#1]
Hi,

Nice work on this, I've started to use this to replace using putcast (which seems to be down more than up these days), so having something that doesn't rely on a 3rd party website to grab stuff from put.io seems the way to go.

I realise this is in it's very early stages :)

However the download example doesn't work, it seems like the client is named wrong, however I've renamed that and it still doesn't seem to be able to download the file.
I think it may have been the recent change to return a promise when no callback is passed in has broken it?

Cheers

Ben

**Comment by alexandrusavin** [comment]
Ups :)

I'll check it in few hours when I get home.

**Comment by alexandrusavin** [comment]
Should be fixed now. Please update and check it out.
