### ISSUE TITLE
Something broken as of a few days ago?

### ISSUE THREAD

**Issue by bbluemel** [alexandrusavin/nodejs-putiosdk#3]
Hi,

This was working perfectly for ages (since my last issue) :) ..

However now it doesn't seem to be working at all, and not giving any indication as to why...

My code:

```
const Client = require('putiosdk');
putioClient = new Client('XXXXXX');
fs = require('fs');


var recurseFolder = (folderid, downloadFolder) => {
    putioClient.file.list({parent_id: folderid}, (err, result) => {
        if ( result && result.files ) {
            for ( var file in result.files ) {
                var thefile = result.files[file];
                if ( thefile.content_type == 'application/x-directory' ) {
                    recurseFolder(thefile.id, downloadFolder);
                } else {
                    switch (thefile.extension) {
                        case 'mkv':
                        case 'mp4':
                            try {
                                fs.statSync(downloadFolder + thefile.name);
                                console.log( thefile.name + ' exists' );   
                            } catch(ex) {
                                console.log( thefile.name + ' doesn\'t exist - downloading' );
                                putioClient.file.download({file_id: thefile.id}).pipe(fs.createWriteStream(downloadFolder + thefile.name));
                            }
                        break;
                    }
                }
            }
        } else {
            console.log( err );
            console.log( result );
            console.log( this );
        }
    });
}
```

Then I just call:
`recurseFolder(0000000, 'I:\\put.io\\');`

In the console I just get:

```
null
{}
{}
```

Any ideas? I'm guessing it's down to either a put.io change or possibly a windows update that may have caused it?

Cheers

Ben

**Comment by alexandrusavin** [comment]
@bbluemel I had the same experience lately. I will check it today. I guess something changed in the api.

**Comment by alexandrusavin** [comment]
As I presumed ... [get files list](https://put.io/v2/docs/files.html#get--files-list) returns 404 for some days. I forwarded this issue to a put.io stuff member and let's see what he has to say.

**Comment by bbluemel** [comment]
Excellent, hopefully they'll get it resolved soon. 

Thanks.

**Comment by alexandrusavin** [comment]
I just published a new version. It seams that I was using the list endpoint wrong (but the api accepted this).

Should work now.

**Comment by bbluemel** [comment]
Hi,

Thanks for looking into it, for some reason that doesn't appear to work - always seems to pull the root directory contents.

Changing that code segment to:

```
    {
        name: 'list',
        route: '/files/list?parent_id=:parent_id',
        method: 'GET',
        returns: ['files', 'parent']
    },
```

Works, but I realise that isn't ideal.

**Comment by alexandrusavin** [comment]
Now! 👍

**Comment by alexandrusavin** [comment]
I have to improve the tests but ... no time

**Comment by bbluemel** [comment]
All good, thanks :+1:
